config/routes.rb
Rails.application.routes.draw do
  resources :waterbills

end

app/models/waterbill.rb
class Waterbill < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/waterbills_controller.rb
class WaterbillsController < ApplicationController
  before_action :set_waterbill, only: [:show, :edit, :update, :destroy]

  # GET /waterbills
  # GET /waterbills.json
  def index
    @waterbills = Waterbill.all
  end

  # GET /waterbills/1
  # GET /waterbills/1.json
  def show
  end

  # GET /waterbills/new
  def new
    @waterbill = Waterbill.new
  end

  # GET /waterbills/1/edit
  def edit
  end

  # POST /waterbills
  # POST /waterbills.json
  def create
    @waterbill = Waterbill.new(waterbill_params)

    respond_to do |format|
      if @waterbill.save
        format.html { redirect_to @waterbill, notice: 'Waterbill was successfully created.' }
        format.json { render :show, status: :created, location: @waterbill }
      else
        format.html { render :new }
        format.json { render json: @waterbill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waterbills/1
  # PATCH/PUT /waterbills/1.json
  def update
    respond_to do |format|
      if @waterbill.update(waterbill_params)
        format.html { redirect_to @waterbill, notice: 'Waterbill was successfully updated.' }
        format.json { render :show, status: :ok, location: @waterbill }
      else
        format.html { render :edit }
        format.json { render json: @waterbill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waterbills/1
  # DELETE /waterbills/1.json
  def destroy
    @waterbill.destroy
    respond_to do |format|
      format.html { redirect_to waterbills_url, notice: 'Waterbill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waterbill
      @waterbill = Waterbill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waterbill_params
      params.require(:waterbill).permit(:consumer, :month, :year, :consumption)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/waterbills_helper.rb
module WaterbillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waterworks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/waterbills/_form.html.erb
<%= form_for(@waterbill) do |f| %>
  <% if @waterbill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waterbill.errors.count, "error") %> prohibited this waterbill from being saved:</h2>

      <ul>
      <% @waterbill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :consumer %><br>
    <%= f.text_field :consumer %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :consumption %><br>
    <%= f.text_field :consumption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waterbills/edit.html.erb
<h1>Editing Waterbill</h1>

<%= render 'form' %>

<%= link_to 'Show', @waterbill %> |
<%= link_to 'Back', waterbills_path %>

app/views/waterbills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Waterbills</h1>

<table>
  <thead>
    <tr>
      <th>Consumer</th>
      <th>Month</th>
      <th>Year</th>
      <th>Consumption</th>
      <th>Custo-mensal</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waterbills.each do |waterbill| %>
      <tr>
        <td><%= waterbill.consumer %></td>
        <td><%= waterbill.month %></td>
        <td><%= waterbill.year %></td>
        <td><%= waterbill.consumption %></td>
        <td><% if waterbill.consumption <= 10 %><% end %></td>
        <td><% if waterbill.consumption >= 11 && waterbill.consumption <= 30 %><%= waterbill.consumption*1 %><%end %></td>
        <td><% if waterbill.consumption >= 31 && waterbill.consumption <= 100 %><%= waterbill.consumption*2 %><%end %></td>
        <td><% if waterbill.consumption <= 101 %><%= waterbill.consumption*5 %><%end %></td>

        <td><% if waterbill.consumption < 10 %><%= "normal" %><% end %></td>
        <td><% if waterbill.consumption >= 10 && waterbill.consumption <= 30 %><%= "overuse" %><%end %></td>
        <td><% if waterbill.consumption >= 31 %><%= "excessive" %><%end %></td>
        <td><%= link_to 'Show', waterbill %></td>
        <td><%= link_to 'Edit', edit_waterbill_path(waterbill) %></td>
        <td><%= link_to 'Destroy', waterbill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Waterbill', new_waterbill_path %>

app/views/waterbills/new.html.erb
<h1>New Waterbill</h1>

<%= render 'form' %>

<%= link_to 'Back', waterbills_path %>

app/views/waterbills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consumer:</strong>
  <%= @waterbill.consumer %>
</p>

<p>
  <strong>Month:</strong>
  <%= @waterbill.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @waterbill.year %>
</p>

<p>
  <strong>Consumption:</strong>
  <%= @waterbill.consumption %>
</p>

<%= link_to 'Edit', edit_waterbill_path(@waterbill) %> |
<%= link_to 'Back', waterbills_path %>